### ISSUE TITLE
Error while fetching C_OrderLine.C_BPartner_ID default value

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#15]
> 2016-09-08 15:05:21.619  WARN 32013 --- [nio-8080-exec-3] de.metas.ui.web.window.model.Document    : Failed initializing DocumentField{fieldName=C_BPartner_ID, documentPath=/W143/1001827/T1/R100172
> 4, value=null, initalValue=null, mandatory=FALSE{mandatory-initial}, readonly=FALSE{readonly-initial}, displayed=FALSE{displayed-initial}}, mode=NewDocument using de.metas.ui.web.window.model.Docum
> ent$Builder$$Lambda$135/2057719503@2bc73a5e. Keeping current initial value.
> 
> org.adempiere.ad.expression.exceptions.ExpressionEvaluationException: Got no result for SELECT (CASE WHEN IsSOTrx='Y' AND IsDropShip='Y' THEN DropShip_BPartner_ID ELSE C_BPartner_ID END) AS Default
> Value FROM C_Order WHERE C_Order_ID=@C_Order_ID@ (SQL: SELECT (CASE WHEN IsSOTrx='Y' AND IsDropShip='Y' THEN DropShip_BPartner_ID ELSE C_BPartner_ID END) AS DefaultValue FROM C_Order WHERE C_Order_
> ID=1001827)
>         at de.metas.ui.web.window.descriptor.sql.SqlDefaultValueExpression.evaluate(SqlDefaultValueExpression.java:123)
>         at de.metas.ui.web.window.descriptor.sql.SqlDefaultValueExpression.evaluate(SqlDefaultValueExpression.java:48)
>         at de.metas.ui.web.window.model.Document.provideFieldInitialValueForNewDocument(Document.java:488)
>         at de.metas.ui.web.window.model.Document.access$900(Document.java:78)
>         at de.metas.ui.web.window.model.Document$Builder.lambda$build$0(Document.java:1368)
>         at de.metas.ui.web.window.model.Document.initializeField(Document.java:405)
>         at de.metas.ui.web.window.model.Document.initializeFields(Document.java:347)
>         at de.metas.ui.web.window.model.Document.access$800(Document.java:78)
>         at de.metas.ui.web.window.model.Document$Builder.build(Document.java:1373)
>         at de.metas.ui.web.window.model.sql.SqlDocumentRepository.createNewDocument(SqlDocumentRepository.java:181)
>         at de.metas.ui.web.window.model.IncludedDocumentsCollection.createNewDocument(IncludedDocumentsCollection.java:166)
>         at de.metas.ui.web.window.model.Document.createIncludedDocument(Document.java:1076)
>         at de.metas.ui.web.window.model.DocumentCollection.getOrCreateDocumentForWriting(DocumentCollection.java:186)
>         at de.metas.ui.web.window.controller.WindowRestController.commit0(WindowRestController.java:238)
>         at de.metas.ui.web.window.controller.WindowRestController.lambda$commit$1(WindowRestController.java:231)
>         at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:151)
>         at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:180)
>         at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:694)
>         at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:606)
>         at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:507)
>         at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:444)
>         at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:429)
>         at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:413)
>         at de.metas.ui.web.window.controller.Execution.callInNewExecution(Execution.java:89)
>         at de.metas.ui.web.window.controller.WindowRestController.commit(WindowRestController.java:231)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
>         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)

**Comment by teosarca** [comment]
cannot reproduce anymore.
