### ISSUE TITLE
date attributes in hu modal window

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui#170]
### Is this a bug or feature request?
bug
### What is the current behavior?
cannot set date attributes in hu modal window
#### Which are the steps to reproduce?
open hu editor, select an LU, add tageslot => 
"Cannot convert value '2017-01-31T00:00:00.000+02:00' (class java.lang.String) to class java.util.Date"
### What is the expected or desired behavior?
date to be set with no errors, Lot-nummer is updated with the tageslot's date number

**Comment by teosarca** [comment]
stacktrace:


```
Got REST exception from handler=public java.util.List<de.met
as.ui.web.window.datatypes.json.JSONDocument> de.metas.ui.web.view.DocumentViewAttributesRestController.processChanges(java.lang.String,int,java.util.List<de.metas.ui.web.window.datatypes.json.JSON
DocumentChangedEvent>)

de.metas.handlingunits.attribute.exceptions.InvalidAttributeValueException: Cannot convert value '2017-02-01T00:00:00.000+02:00' (class java.lang.String) to class java.util.Date
        at de.metas.handlingunits.attribute.impl.AbstractAttributeValue.valueToDate(AbstractAttributeValue.java:648)
        at de.metas.handlingunits.attribute.impl.AbstractAttributeValue.setValue(AbstractAttributeValue.java:207)
        at de.metas.handlingunits.attribute.propagation.impl.AbstractHUAttributePropagator.setStorageValue(AbstractHUAttributePropagator.java:87)
        at de.metas.handlingunits.attribute.propagation.impl.TopDownHUAttributePropagator.setValue(TopDownHUAttributePropagator.java:92)
        at de.metas.handlingunits.attribute.propagation.impl.TopDownHUAttributePropagator.propagateValue(TopDownHUAttributePropagator.java:66)
        at de.metas.handlingunits.attribute.storage.impl.AbstractAttributeStorage.setValue(AbstractAttributeStorage.java:737)
        at de.metas.handlingunits.attribute.storage.impl.AbstractAttributeStorage.setValue(AbstractAttributeStorage.java:658)
        at de.metas.ui.web.handlingunits.HUDocumentViewAttributes.processChange(HUDocumentViewAttributes.java:184)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at de.metas.ui.web.handlingunits.HUDocumentViewAttributes.processChanges(HUDocumentViewAttributes.java:168)
        at de.metas.ui.web.view.DocumentViewAttributesRestController.lambda$processChanges$0(DocumentViewAttributesRestController.java:111)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:193)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:764)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:676)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:577)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:508)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:493)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:470)
        at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$0(Execution.java:194)
        at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)
        at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)
        at de.metas.ui.web.window.controller.Execution.callInNewExecution(Execution.java:88)
        at de.metas.ui.web.view.DocumentViewAttributesRestController.processChanges(DocumentViewAttributesRestController.java:107)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)

```

**Comment by metas-lc** [comment]
IT https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-934.md OK
