### ISSUE TITLE
Get rid of "Assumption failure: Parameter quickInputDescriptor is not null"

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#175]
Solution: advice the webui frontend that there is no quick input for that tab, so the frontend shall:
* hide the batch entry button
* not query for the quick input descriptor

```
Assumption failure: Parameter quickInputDescriptor is not null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.adempiere.util.Check.mkEx(Check.java:109)
        at org.adempiere.util.Check.throwOrLogEx(Check.java:120)
        at org.adempiere.util.Check.assume(Check.java:163)
        at org.adempiere.util.Check.assumeNotNull(Check.java:258)
        at org.adempiere.util.Check.assumeNotNull(Check.java:244)
        at de.metas.ui.web.quickinput.QuickInput$Builder.getQuickInputDescriptor(QuickInput.java:255)
        at de.metas.ui.web.quickinput.QuickInput$Builder.access$100(QuickInput.java:218)
        at de.metas.ui.web.quickinput.QuickInput.<init>(QuickInput.java:81)
        at de.metas.ui.web.quickinput.QuickInput.<init>(QuickInput.java:52)
        at de.metas.ui.web.quickinput.QuickInput$Builder.build(QuickInput.java:232)
        at de.metas.ui.web.quickinput.WindowQuickInputRestController.lambda$createQuickInput$3(WindowQuickInputRestController.java:222)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:193)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:764)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:676)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:577)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:508)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:493)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:470)
        at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$0(Execution.java:194)
        at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)
        at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)
        at de.metas.ui.web.window.controller.Execution.callInNewExecution(Execution.java:88)
        at de.metas.ui.web.quickinput.WindowQuickInputRestController.createQuickInput(WindowQuickInputRestController.java:218)
        at de.metas.ui.web.quickinput.WindowQuickInputRestController.create(WindowQuickInputRestController.java:119)

```

**Comment by teosarca** [comment]
Fixed in #201
