### ISSUE TITLE
cannot add a bpartner in manual invoice

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui#218]
### Is this a bug or feature request?
bug
### What is the current behavior?
NPE in invoice when adding a bpartner
#### Which are the steps to reproduce?
1. go to sales or purchase invoice
2. create a new one
3. add a bpartner => NPE
### What is the expected or desired behavior?
add the bpartner without errors

**Comment by teosarca** [comment]
stack trace is:

```

with path [] threw exception [Request processing failed; nested exception is org.adempiere.ad.callout.exceptions.CalloutExecutionException: java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
        at de.metas.edi.api.impl.EDIDocumentBL.updateEdiEnabled(EDIDocumentBL.java:82)
        at de.metas.edi.callout.C_Invoice.onC_BPartner_ID(C_Invoice.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.compiere.model.CalloutEngine.lambda$createCalloutMethodExecutor$2(CalloutEngine.java:195)
        at org.compiere.model.CalloutEngine.start(CalloutEngine.java:71)
        at org.adempiere.ad.callout.api.impl.MethodNameCalloutInstance.execute(MethodNameCalloutInstance.java:120)
        at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:262)
        at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:119)
        at de.metas.ui.web.window.model.Document.setValue(Document.java:1103)
        at de.metas.ui.web.window.model.Document.processValueChange(Document.java:1004)
        at de.metas.ui.web.window.model.Document.processValueChanges(Document.java:1019)
        at de.metas.ui.web.window.controller.WindowRestController.lambda$patchDocument0$3(WindowRestController.java:278)
        at de.metas.ui.web.window.model.DocumentCollection.lambda$forDocumentWritable$0(DocumentCollection.java:161)
        at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentWritable(DocumentCollection.java:204)
        at de.metas.ui.web.window.model.DocumentCollection.forDocumentWritable(DocumentCollection.java:145)
        at de.metas.ui.web.window.controller.WindowRestController.patchDocument0(WindowRestController.java:277)
        at de.metas.ui.web.window.controller.WindowRestController.lambda$patchDocument$2(WindowRestController.java:272)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:193)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:764)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:676)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:577)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:508)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:493)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:470)
        at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$0(Execution.java:194)
        at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)
        at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)
        at de.metas.ui.web.window.controller.Execution.callInNewExecution(Execution.java:88)
        at de.metas.ui.web.window.controller.WindowRestController.patchDocument(WindowRestController.java:272)
        at de.metas.ui.web.window.controller.WindowRestController.patchRootDocument(WindowRestController.java:241)
        at sun.reflect.GeneratedMethodAccessor258.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)


```

**Comment by teosarca** [comment]
regression test on swing: do the same, make sure the IsEdiEnabled flag is updated

**Comment by metas-dh** [comment]
Results of IT 1

tested on w101:
* no more NPE when setting a bpartner in manual invoice, OK
* follow up for doc no., https://github.com/metasfresh/metasfresh-webui/issues/235
